name: CI

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:
jobs:
  build-and-released:
    run-on: ubuntu-latest
  steps:
    - uses:actions/checkout@v3

    - name: Run a one-line script
      run:echo hello, world!

    - name: Run a multi-line script
    run: | 
      echo add other action to build
      echo test and deploy your project.
      
